name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
 build:
   runs-on: ubuntu-latest
   steps:        
     - uses: appleboy/scp-action@master
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        target: "~/home/ec2-user/supply-chain"
   
     - name: Update API   
       uses: appleboy/ssh-action@master
       with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script:
         cd /home/ec2-user/supply-chain && docker-compose up -d --build api-supply-chain
